### ISSUE TITLE
Can't set caller offset

### ISSUE THREAD

**Issue by efritz** [aphistic/gomol#23]
If filename and line numbers are turned on, but I have a wrapper around a the log calls, then the line number is always at this abstraction level. I'd like to be able to do something like `gomol.SetCallerOffset(1)` which would look one more call up the stack before returning.

Otherwise, since it doesn't look like your caller information is based on index but on strings, provide a way to blacklist packages so that it will skip gomol *and* this particular filename or package.

**Comment by aphistic** [comment]
Makes sense. I'll probably look into changing it to use an index instead of strings.

**Comment by efritz** [comment]
You'll have to be careful that all code paths to this function are the same depth (that may be tricky).

**Comment by aphistic** [comment]
Yeah, I was thinking about that.  I think I'd much rather deal with that issue than the strings I'm dealing with now.
